on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        name: Continuous Integration
        permissions:
            contents: read
            id-token: write
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@4

            - name: Install dependencies
              run: npm install

            - name: Formatting
              run: npm run format:check

            - name: License check
              run: npx lice src -a

            - name: Linting
              run: npm run lint

            - name: Build
              run: npx tsc
