name: Release

on:
    release:
        types: [created]

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml
        permissions:
            contents: write
            id-token: write
            pages: write
    release:
        runs-on: ubuntu-latest
        needs: ci
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup npm authenication
              uses: actions/setup-node@v3
              with:
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Publish
              run: npm publish --access=public --provenance
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
